# Default configuration
DEBUG = False
SECRET_KEY = 'G#ODF)lpo4i2r:"<230kfas;dfk30%'
DURACLOUD_URL = 'https://foo.duracloud.org/'
DURACLOUD_USERNAME = 'foo'
DURACLOUD_PASSWORD = 'bar'
DURASTREAM_TIMEOUT_HRS = 8
DURACLOUD_SPACE_CACHE_DIR = '/tmp/durastream_cache'
IP_RULES_CONFIG = 'ip_rules.cfg'
